language: java
install: ./mvnw -DskipTests=true -Dgpg.skip=true install javadoc:javadoc
addons:
    apt:
        packages:
            - openjdk-6-jdk
jdk:
    - oraclejdk8
    - openjdk7
    - openjdk6
